//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace UmbracoLearning.Domain.Content
{
	/// <summary>HomePage</summary>
	[PublishedContentModel("homePage")]
	public partial class HomePage : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "homePage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HomePage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HomePage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Article Body Text 1
		///</summary>
		[ImplementPropertyType("articleBodyText1")]
		public IHtmlString ArticleBodyText1
		{
			get { return this.GetPropertyValue<IHtmlString>("articleBodyText1"); }
		}

		///<summary>
		/// Article Body Text 2
		///</summary>
		[ImplementPropertyType("articleBodyText2")]
		public IHtmlString ArticleBodyText2
		{
			get { return this.GetPropertyValue<IHtmlString>("articleBodyText2"); }
		}

		///<summary>
		/// Article Title 1
		///</summary>
		[ImplementPropertyType("articleTitle1")]
		public string ArticleTitle1
		{
			get { return this.GetPropertyValue<string>("articleTitle1"); }
		}

		///<summary>
		/// Article Title 2
		///</summary>
		[ImplementPropertyType("articleTitle2")]
		public string ArticleTitle2
		{
			get { return this.GetPropertyValue<string>("articleTitle2"); }
		}

		///<summary>
		/// Aside Text
		///</summary>
		[ImplementPropertyType("asideText")]
		public IHtmlString AsideText
		{
			get { return this.GetPropertyValue<IHtmlString>("asideText"); }
		}

		///<summary>
		/// Aside Title
		///</summary>
		[ImplementPropertyType("asideTitle")]
		public string AsideTitle
		{
			get { return this.GetPropertyValue<string>("asideTitle"); }
		}

		///<summary>
		/// Body Text: The main content of the page
		///</summary>
		[ImplementPropertyType("bodyText")]
		public IHtmlString BodyText
		{
			get { return this.GetPropertyValue<IHtmlString>("bodyText"); }
		}

		///<summary>
		/// Footer Text: Copyright notice for the footer
		///</summary>
		[ImplementPropertyType("footerText")]
		public string FooterText
		{
			get { return this.GetPropertyValue<string>("footerText"); }
		}

		///<summary>
		/// Page Title: Title of the page
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return this.GetPropertyValue<string>("pageTitle"); }
		}
	}
}
